# To use this Makefile, place it in the
# same directory as the source code
# (don't rename the Makefile).
# To compile:  make compile 
# To run example(s): make run
# To cleanup:  make clean
compile:
	g++ -g -Wall -std=gnu++11 lab01.cpp -o lab01.out

run:	
	./lab01.out -f1 182
	./lab01.out -f2 182

clean:
	rm *.out
